#!/usr/bin/env python3
"""Non-autoregressive backing-vocal inference for one-to-one styles."""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path
from typing import Any, Callable

import mlx.core as mx


REPO_ROOT = Path(__file__).resolve().parents[2]
TRANSFORMER_SCRIPTS = REPO_ROOT / "scripts" / "backing_transformer"
if str(TRANSFORMER_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(TRANSFORMER_SCRIPTS))

from model import BackingTransformer, ModelConfig, OFFSET_MIN, continuous_features  # noqa: E402
from generate_backing_vocals import (  # noqa: E402
    build_beat_map,
    build_windows,
    chord_at,
    finalize_generated_notes,
    flatten_note_windows,
    harmonic_postprocess,
    midi_to_pitch,
    normalize_chords,
    normalize_lead,
    normalize_tempos,
    stitch_notes,
    style_by_id,
    write_debug_dsl,
)


DEFAULT_TRANSFORMER = Path.home() / ".synthetic_obsidian" / "models" / "backing_vocals" / "backing_transformer_v1"
NOTE_TO_PC = {"C": 0, "C#": 1, "DB": 1, "D": 2, "D#": 3, "EB": 3, "E": 4, "F": 5, "F#": 6, "GB": 6, "G": 7, "G#": 8, "AB": 8, "A": 9, "A#": 10, "BB": 10, "B": 11}
DYNAMIC_STYLE_ID = "DYNAMIC_CP"
DYNAMIC_SOURCE_STYLES = ("CONTRARY", "OBLIQUE", "THIRD_UP")


def load_transformer(path: Path = DEFAULT_TRANSFORMER) -> tuple[BackingTransformer, ModelConfig]:
    config_json = json.loads((path / "config.json").read_text(encoding="utf-8"))
    config = ModelConfig(
        styles=tuple(config_json["styles"]),
        dimensions=int(config_json["dimensions"]),
        heads=int(config_json["heads"]),
        layers=int(config_json["layers"]),
        mlp_dimensions=int(config_json["mlp_dimensions"]),
        max_notes=int(config_json["max_notes"]),
    )
    model = BackingTransformer(config)
    model.load_weights(str(path / "model.safetensors"))
    model.train(False)
    mx.eval(model.parameters())
    return model, config


def supports_style(config: ModelConfig, style_id: str) -> bool:
    if style_id == DYNAMIC_STYLE_ID:
        return all(source_style in config.styles for source_style in DYNAMIC_SOURCE_STYLES)
    return style_id in config.styles


def generate_with_transformer(
    request: dict[str, Any],
    args: Any,
    model: BackingTransformer,
    config: ModelConfig,
    stream_callback: Callable[[dict[str, Any]], None] | None = None,
) -> dict[str, Any]:
    style = style_by_id(str(request.get("style_id", "")))
    if style is None or not supports_style(config, style["id"]):
        raise ValueError(f"Compact Transformer does not support style {request.get('style_id')}")
    tempo_segments = normalize_tempos(request.get("tempo_segments"), float(request.get("bpm") or 120.0), float(request.get("duration") or 0.0))
    beat_map = build_beat_map(tempo_segments)
    lead = normalize_lead(request.get("lead_notes"), beat_map)
    chords = normalize_chords(request.get("chords"), beat_map)
    if not lead or not chords:
        raise ValueError("Compact Transformer needs lead notes and chords")

    max_notes = min(config.max_notes, max(1, int(getattr(args, "max_lead_notes", config.max_notes))))
    windows = build_windows(lead, max_notes, float(getattr(args, "max_gap_beats", 2.0)))
    generated_sets = []
    for window_index, window in enumerate(windows, start=1):
        notes = predict_window(request, style["id"], window, chords, model, config)
        generated_sets.append(notes)
        if stream_callback is not None:
            stream_callback(
                {
                    "type": "window",
                    "engine": "compact_transformer",
                    "style_id": style["id"],
                    "style_name": style["name"],
                    "window_index": window_index,
                    "window_count": len(windows),
                    "note_count": sum(len(items) for items in generated_sets),
                    "warnings": [],
                    "notes": finalize_generated_notes(generated_sets, style, chords, str(request.get("key") or "C major"), beat_map),
                }
            )
    corrected = harmonic_postprocess(flatten_note_windows(generated_sets), chords, str(request.get("key") or "C major"), style["id"])
    debug_path = write_debug_dsl(request, style, chords, lead, [corrected], ["Generated by compact non-autoregressive Transformer with harmonic validation."])
    notes = stitch_notes([corrected], style, beat_map)
    return {
        "engine": "compact_transformer",
        "style_id": style["id"],
        "style_name": style["name"],
        "window_count": len(windows),
        "note_count": len(notes),
        "warnings": [],
        "debug_dsl_path": str(debug_path) if debug_path else "",
        "notes": notes,
    }


def predict_window(
    request: dict[str, Any],
    style_id: str,
    lead: list[dict[str, Any]],
    chords: list[dict[str, Any]],
    model: BackingTransformer,
    config: ModelConfig,
) -> list[dict[str, Any]]:
    key_pc, key_mode = parse_key(str(request.get("key") or "C major"))
    meter = meter_numerator(str(request.get("meter") or "4/4"))
    compact_notes = []
    previous_pitch = int(lead[0]["midi_note"])
    previous_end = float(lead[0]["start"])
    previous_phrase = ""
    for index, note in enumerate(lead):
        chord = chord_at(chords, float(note["start"]))
        pitch = int(note["midi_note"])
        phrase = str(note.get("phrase_id") or "")
        compact_notes.append(
            {
                "pitch": pitch,
                "duration": float(note["duration"]),
                "gap": max(0.0, float(note["start"]) - previous_end),
                "lead_delta": max(-24, min(24, pitch - previous_pitch)),
                "beat": float(note.get("beat") or 1.0),
                "meter": meter,
                "velocity": int(note.get("velocity") or 80),
                "phrase_start": index == 0 or phrase != previous_phrase,
                "chord_root": note_pc(str(chord.get("root") or "")),
                "chord_quality": quality_id(str(chord.get("quality") or "unknown")),
                "chord_mask": chord_pitch_mask(chord),
            }
        )
        previous_pitch = pitch
        previous_end = float(note["start"]) + float(note["duration"])
        previous_phrase = phrase

    length = len(compact_notes)
    pitch = mx.array([[note["pitch"] for note in compact_notes]])
    chord_root = mx.array([[note["chord_root"] for note in compact_notes]])
    chord_quality = mx.array([[note["chord_quality"] for note in compact_notes]])
    continuous = mx.array([[continuous_features(note) for note in compact_notes]])
    valid = mx.ones((1, length), dtype=mx.bool_)
    def infer(style_index: int) -> mx.array:
        return model(
            pitch,
            mx.array([style_index]),
            chord_root,
            chord_quality,
            mx.array([key_pc]),
            mx.array([key_mode]),
            continuous,
            valid,
        )

    if style_id == DYNAMIC_STYLE_ID:
        source_logits = {
            source_style: infer(config.styles.index(source_style))
            for source_style in DYNAMIC_SOURCE_STYLES
        }
        mx.eval(*source_logits.values())
        offsets = decode_dynamic_counterpoint(source_logits, lead, compact_notes)
    else:
        logits = infer(config.styles.index(style_id))
        offsets = (mx.argmax(logits, axis=-1)[0].astype(mx.int32) + OFFSET_MIN).tolist()
    output = []
    for index, (source, offset) in enumerate(zip(lead, offsets, strict=True), start=1):
        midi = max(24, min(96, int(source["midi_note"]) + int(offset)))
        output.append(
            {
                "id": f"{style_id.lower()}_compact_{index:04d}",
                "part": "backing",
                "strategy": style_id.lower(),
                "start": float(source["start"]),
                "duration": max(0.05, float(source["duration"])),
                "midi_note": midi,
                "pitch": midi_to_pitch(midi),
                "velocity": 74,
                "lyric": source.get("syllable") or "",
                "syllable_id": source.get("syllable_id") or "",
                "legato_from_previous": bool(source.get("legato_from_previous")),
                "legato_to_next": bool(source.get("legato_to_next")),
                "melisma_continuation": bool(source.get("melisma_continuation")),
                "source_lead_ref": source["id"],
            }
        )
    return output


def decode_dynamic_counterpoint(
    source_logits: dict[str, mx.array],
    lead: list[dict[str, Any]],
    compact_notes: list[dict[str, Any]],
) -> list[int]:
    """Decode a phrase from learned style probabilities with varied voice leading."""
    weights = {"CONTRARY": 0.40, "OBLIQUE": 0.35, "THIRD_UP": 0.25}
    log_probabilities = {
        style: [_log_softmax(row) for row in logits[0].tolist()]
        for style, logits in source_logits.items()
    }
    blended = []
    for note_index in range(len(lead)):
        blended.append(
            [
                sum(weights[style] * log_probabilities[style][note_index][class_index] for style in DYNAMIC_SOURCE_STYLES)
                for class_index in range(len(log_probabilities[DYNAMIC_SOURCE_STYLES[0]][note_index]))
            ]
        )

    # score, offsets, previous output pitch, previous lead interval,
    # parallel run, repeated-interval run, previous motion, motion run
    beams: list[tuple[float, list[int], int | None, int | None, int, int, str, int]] = [
        (0.0, [], None, None, 0, 0, "", 0)
    ]
    beam_width = 32

    for note_index, (source, features) in enumerate(zip(lead, compact_notes, strict=True)):
        lead_pitch = int(source["midi_note"])
        chord_mask = int(features["chord_mask"])
        candidates = set(_top_indices(blended[note_index], 10))
        for style in DYNAMIC_SOURCE_STYLES:
            candidates.update(_top_indices(log_probabilities[style][note_index], 4))
        if chord_mask:
            for class_index in range(len(blended[note_index])):
                output_pitch = lead_pitch + class_index + OFFSET_MIN
                if 24 <= output_pitch <= 96 and chord_mask & (1 << (output_pitch % 12)):
                    candidates.add(class_index)

        expanded: list[tuple[float, list[int], int | None, int | None, int, int, str, int]] = []
        for state in beams:
            score, chosen, previous_output, previous_interval, parallel_run, interval_run, previous_motion, motion_run = state
            if note_index > 0 and bool(features["phrase_start"]):
                previous_output = None
                previous_interval = None
                parallel_run = 0
                interval_run = 0
                previous_motion = ""
                motion_run = 0

            for class_index in candidates:
                offset = class_index + OFFSET_MIN
                output_pitch = lead_pitch + offset
                if output_pitch < 24 or output_pitch > 96:
                    continue

                candidate_score = score + blended[note_index][class_index]
                pitch_class = output_pitch % 12
                if chord_mask:
                    candidate_score += 0.65 if chord_mask & (1 << pitch_class) else -0.30

                consonance = abs(offset) % 12
                candidate_score += {
                    0: -0.55,
                    1: -1.20,
                    2: -1.00,
                    3: 0.18,
                    4: 0.24,
                    5: 0.04,
                    6: -1.25,
                    7: 0.12,
                    8: 0.18,
                    9: 0.20,
                    10: -0.82,
                    11: -1.00,
                }[consonance]
                if output_pitch < 40 or output_pitch > 84:
                    candidate_score -= 0.08 * min(abs(output_pitch - 40), abs(output_pitch - 84))

                next_parallel_run = 0
                next_motion = ""
                next_motion_run = 0
                next_interval_run = 1
                if previous_output is not None:
                    lead_delta = int(features["lead_delta"])
                    backing_delta = output_pitch - previous_output
                    leap = abs(backing_delta)
                    if leap <= 2:
                        candidate_score += 0.16
                    elif leap > 7:
                        candidate_score -= 0.22 * (leap - 7)

                    if abs(lead_delta) >= 1 and backing_delta == 0:
                        next_motion = "oblique"
                        candidate_score += 0.58
                    elif lead_delta * backing_delta < 0:
                        next_motion = "contrary"
                        candidate_score += 0.68
                    elif lead_delta * backing_delta > 0:
                        next_motion = "parallel"
                        candidate_score += 0.10
                    else:
                        next_motion = "static"

                    next_motion_run = motion_run + 1 if next_motion == previous_motion else 1
                    if next_motion_run > 2:
                        run_penalty = 0.95 if next_motion == "oblique" else 0.28
                        candidate_score -= run_penalty * (next_motion_run - 2)

                    next_parallel_run = parallel_run + 1 if next_motion == "parallel" else 0
                    if next_parallel_run > 2:
                        candidate_score -= 0.40 * (next_parallel_run - 2)

                if previous_interval is not None and offset == previous_interval:
                    next_interval_run = interval_run + 1
                    if next_interval_run > 2:
                        candidate_score -= 0.34 * (next_interval_run - 2)

                expanded.append(
                    (
                        candidate_score,
                        [*chosen, offset],
                        output_pitch,
                        offset,
                        next_parallel_run,
                        next_interval_run,
                        next_motion,
                        next_motion_run,
                    )
                )

        if not expanded:
            return [0] * len(lead)
        expanded.sort(key=lambda item: item[0], reverse=True)
        beams = expanded[:beam_width]

    return beams[0][1]


def _log_softmax(values: list[float]) -> list[float]:
    maximum = max(values)
    normalizer = maximum + math.log(sum(math.exp(value - maximum) for value in values))
    return [value - normalizer for value in values]


def _top_indices(values: list[float], count: int) -> list[int]:
    return sorted(range(len(values)), key=values.__getitem__, reverse=True)[:count]


def note_pc(note: str) -> int:
    match = re.match(r"^([A-Ga-g](?:#|b)?)", note.strip())
    return NOTE_TO_PC.get(match.group(1).upper(), 12) if match else 12


def parse_key(key: str) -> tuple[int, int]:
    pieces = key.split()
    lowered = key.lower()
    return (note_pc(pieces[0]) if pieces else 12, 2 if "minor" in lowered else 1 if "major" in lowered else 0)


def meter_numerator(meter: str) -> int:
    try:
        return max(1, min(12, int(meter.split("/", 1)[0])))
    except ValueError:
        return 4


def chord_pitch_mask(chord: dict[str, Any]) -> int:
    mask = 0
    for note in chord.get("notes", []) or []:
        pc = note_pc(str(note))
        if pc < 12:
            mask |= 1 << pc
    return mask


def quality_id(quality: str) -> int:
    normalized = quality.lower().strip()
    direct = {"unknown": 0, "major": 1, "minor": 2, "dominant": 3, "major7": 4, "minor7": 5, "diminished": 6, "half-diminished": 7, "augmented": 8, "sus2": 9, "sus4": 10, "sixth": 11, "minor6": 12}
    if normalized in direct:
        return direct[normalized]
    if "minor" in normalized:
        return 2
    if "major" in normalized:
        return 1
    if "dim" in normalized:
        return 6
    if "sus2" in normalized:
        return 9
    if "sus" in normalized:
        return 10
    return 0
